package com.example.backend.dto.caseDTOS;

import com.example.backend.model.cases.PaymentStatus; // Ensure this import is correct

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Map;
import java.util.UUID;

/**
 * Data Transfer Object for creating a new case. This object's structure
 * directly matches the fields on the "Create Case" form in the UI.
 */
public class CreateCaseRequest {

    // --- NEW FIELD FOR DYNAMIC, TYPE-SPECIFIC DATA ---
    private Map<String, Object> additionalDetails;

    public Map<String, Object> getAdditionalDetails() { return additionalDetails; }
    public void setAdditionalDetails(Map<String, Object> additionalDetails) { this.additionalDetails = additionalDetails; }

    private UUID existingClientId;

    public UUID getExistingClientId() {
        return existingClientId;
    }

    public void setExistingClientId(UUID existingClientId) {
        this.existingClientId = existingClientId;
    }

    // --- Parties Involved ---
    private String clientName;
    private String clientPhone;
    private String clientEmail;
    private String opposingPartyName;
    private UUID associatedJuniorId; // The ID of the junior selected from the dropdown

    // --- Case Details ---
    private String caseNumber;
    private String court;
    private String courtType; //
    private LocalDate initialHearingDate; // The date of the very first hearing
    private String description;
    private String caseType;

    // --- Financials ---
    private BigDecimal agreedFee;
    private PaymentStatus paymentStatus;

    // --- Getters and Setters for ALL fields ---
    // (Generated by IDE)


    public String getCourtType() {
        return courtType;
    }

    public void setCourtType(String courtType) {
        this.courtType = courtType;
    }

    public String getCaseType() {
        return caseType;
    }

    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientPhone() {
        return clientPhone;
    }

    public void setClientPhone(String clientPhone) {
        this.clientPhone = clientPhone;
    }

    public String getClientEmail() {
        return clientEmail;
    }

    public void setClientEmail(String clientEmail) {
        this.clientEmail = clientEmail;
    }

    public String getOpposingPartyName() {
        return opposingPartyName;
    }

    public void setOpposingPartyName(String opposingPartyName) {
        this.opposingPartyName = opposingPartyName;
    }

    public UUID getAssociatedJuniorId() {
        return associatedJuniorId;
    }

    public void setAssociatedJuniorId(UUID associatedJuniorId) {
        this.associatedJuniorId = associatedJuniorId;
    }

    public String getCaseNumber() {
        return caseNumber;
    }

    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber;
    }

    public String getCourt() {
        return court;
    }

    public void setCourt(String court) {
        this.court = court;
    }

    public LocalDate getInitialHearingDate() {
        return initialHearingDate;
    }

    public void setInitialHearingDate(LocalDate initialHearingDate) {
        this.initialHearingDate = initialHearingDate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getAgreedFee() {
        return agreedFee;
    }

    public void setAgreedFee(BigDecimal agreedFee) {
        this.agreedFee = agreedFee;
    }

    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
}