package com.example.backend.dto.caseDTOS;

import com.example.backend.model.cases.CaseStatus;
import com.example.backend.model.cases.PaymentStatus;
import java.math.BigDecimal;

/**
 * Data Transfer Object for updating an existing case. Contains only the fields
 * that a user is permitted to change after a case has been created.
 */
public class UpdateCaseRequest {

    // --- Core Details ---
    private String caseTitle;
    private String caseNumber;
    private String caseType;
    private String courtName;
    private String courtType;
    private String description;

    // --- Parties ---
    private String clientName;
    private String clientPhone;
    private String clientEmail;
    private String opposingPartyName;

    // --- Financials ---
    private BigDecimal agreedFee;
    private PaymentStatus paymentStatus;

    // --- Status ---
    private CaseStatus status;

    // --- Getters and Setters for ALL fields ---
    // (Generated by IDE)

    public String getCourtType() {
        return courtType;
    }

    public void setCourtType(String courtType) {
        this.courtType = courtType;
    }

    public String getCaseTitle() {
        return caseTitle;
    }

    public void setCaseTitle(String caseTitle) {
        this.caseTitle = caseTitle;
    }

    public String getCaseNumber() {
        return caseNumber;
    }

    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber;
    }

    public String getCaseType() {
        return caseType;
    }

    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }

    public String getCourtName() {
        return courtName;
    }

    public void setCourtName(String courtName) {
        this.courtName = courtName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientPhone() {
        return clientPhone;
    }

    public void setClientPhone(String clientPhone) {
        this.clientPhone = clientPhone;
    }

    public String getClientEmail() {
        return clientEmail;
    }

    public void setClientEmail(String clientEmail) {
        this.clientEmail = clientEmail;
    }

    public String getOpposingPartyName() {
        return opposingPartyName;
    }

    public void setOpposingPartyName(String opposingPartyName) {
        this.opposingPartyName = opposingPartyName;
    }

    public BigDecimal getAgreedFee() {
        return agreedFee;
    }

    public void setAgreedFee(BigDecimal agreedFee) {
        this.agreedFee = agreedFee;
    }

    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public CaseStatus getStatus() {
        return status;
    }

    public void setStatus(CaseStatus status) {
        this.status = status;
    }
}