@auth_token = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJiN2JhZmIyZjEwY2FlMmIxZjA3ZjM4MTZjNTQyMmJlY2NhNWMyMjMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXR0b3JuZXktNDU4NjIiLCJhdWQiOiJhdHRvcm5leS00NTg2MiIsImF1dGhfdGltZSI6MTc1NTEwODM3NywidXNlcl9pZCI6IlQwVjF5RjV2UUFoTDVlWmt0OTNGVFdCYjlwTjIiLCJzdWIiOiJUMFYxeUY1dlFBaEw1ZVprdDkzRlRXQmI5cE4yIiwiaWF0IjoxNzU1MTA4Mzc3LCJleHAiOjE3NTUxMTE5NzcsImVtYWlsIjoiZGFyc2hhbmEyMDIxc3VqYW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGFyc2hhbmEyMDIxc3VqYW5AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.L2MTUKZSOYMa9HB2ayX_3OeufDUmfbq8aQ7xQdUJUn5dq7GBOoAXeyDqqdtR8T6oFwhuEZDIEdC82R87YDt-JvoMpc6kQR8qRZI9jjCSQzf3sviO4VfBoiWix3eSRx4qMCwO8pDJQFhV2lELxHfVXK0SPOOVSaFkJ4LtI5l8Tj9nL9vmXavHq90KbWU-4W5mwx2VraLeSG_ypSn5y_oFg-nV0TwJnvrgxaeUpQBFSbqq27V6FqU1jQqtTqp5rNVCzvs0BOcz81x4oXVjbP10RN_BtX9o_VS5qitG0xUDgXhffdrUPax35u1bkYcNzfcCq9Y3V58_9wcscGRPdpQfBA


POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: {{auth_token}}

{
  "title": "New Task",
  "description": "This is a new task created via HTTP request.",
    "dueDate": "2023-12-31T23:59:59Z",
    "assignedTo": "223"
}