@auth_token = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1YTAwNWU5N2NiMWU0MjczMDBlNTJjZGQ1MGYwYjM2Y2Q4MDYyOWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXR0b3JuZXktY2hhdCIsImF1ZCI6ImF0dG9ybmV5LWNoYXQiLCJhdXRoX3RpbWUiOjE3NjA2NzI4MzgsInVzZXJfaWQiOiJIellnRzZsVGhUUlN4RjFCdzZLR2JyUzRNTEIzIiwic3ViIjoiSHpZZ0c2bFRoVFJTeEYxQnc2S0diclM0TUxCMyIsImlhdCI6MTc2MDY3MjgzOCwiZXhwIjoxNzYwNjc2NDM4LCJlbWFpbCI6InNkYXJzaGFuYXVuaS4yMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJzZGFyc2hhbmF1bmkuMjFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.gT3mXz4nhf3qJt_UGQ8hYcxGFkWvyhcbOEzf_EN423Pg8JfTcn9y14b6-3psKV_RBXVP7tCfBEoSyHRz4E1EHJb1WtqJpDAVs_dFVSXvxbBPIKTsHz6ZCkb5yhG1BKbeD-0JaNvB_hXefMHUHcnKCGEpc8p-Ic776o7n72QPkCpyXeqokISqs3TotErP66ktF2OlaR58wKBswpidOKtFIY1fqG_v011vbCydVjyczJ_Zy3dWXE4Rj9XY7oLqOO3vYVfWd_aul7pRwL0x7HHL1JMYx1v4I7cMJPfIG4VkBXUSSDOZGuznPT-G97g066B5pD2WHcxC7J3Dk_EykT3igA
#GET http://localhost:8080/api/tasks/123
#Accept: application/json
#Authorization: {{auth_token}}

###
### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: {{auth_token}}

{
  "title": "idam nadu",
  "description": "loku case ekak nh",
  "assignedToUserId": "ff9f0c07-091a-40be-b80c-eed340e98ca7",
  "type": "document"
}

