### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

@auth_token = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU3YmZiMmExMWRkZmZjMGFkMmU2ODE0YzY4NzYzYjhjNjg3NTgxZDgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXR0b3JuZXktNDU4NjIiLCJhdWQiOiJhdHRvcm5leS00NTg2MiIsImF1dGhfdGltZSI6MTc1NTUwNjg1OSwidXNlcl9pZCI6IlQwVjF5RjV2UUFoTDVlWmt0OTNGVFdCYjlwTjIiLCJzdWIiOiJUMFYxeUY1dlFBaEw1ZVprdDkzRlRXQmI5cE4yIiwiaWF0IjoxNzU1NTA2ODU5LCJleHAiOjE3NTU1MTA0NTksImVtYWlsIjoiZGFyc2hhbmEyMDIxc3VqYW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGFyc2hhbmEyMDIxc3VqYW5AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.dAGbhjnXOoGeAU9IffCjePGq_a0PnKj-7wUmFgDT7vzYNc64FdAkHR2iMD7RFEKwKET3CLWMZrVYG6Vud-xg63atcziNOMIyIp0MbfM8SnZ6KmgTUNEKdhhAAcfCKbkTZEDHHSJF6qBBbbkCa2FLlIrTP0y_T3c7179t52b0FcJtOX64SDfSX47TjjX3n9f1V_1De2MzDmOP4LBAQaR3nIO7ahbvWL58cVAkvHEGkNKW13qn7UvVZt1A6GUsSoLyxUGYEiZ_PlD6X35VLm73JLAKUuvJt71p0kRccC-F796tt23AwlYMKNGuvPhY9fEPUX7vucacSMaAgZr43KJPQg
POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: {{auth_token}}

{
  "title": "idam nadu",
  "description": "loku case ekak nh",
  "assignedToUserId": "ff9f0c07-091a-40be-b80c-eed340e98ca7",
  "type": "document"
}