### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

@auth_token = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1YTAwNWU5N2NiMWU0MjczMDBlNTJjZGQ1MGYwYjM2Y2Q4MDYyOWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXR0b3JuZXktNDU4NjIiLCJhdWQiOiJhdHRvcm5leS00NTg2MiIsImF1dGhfdGltZSI6MTc2MDYxMzQ5NywidXNlcl9pZCI6IlQwVjF5RjV2UUFoTDVlWmt0OTNGVFdCYjlwTjIiLCJzdWIiOiJUMFYxeUY1dlFBaEw1ZVprdDkzRlRXQmI5cE4yIiwiaWF0IjoxNzYwNjEzNDk3LCJleHAiOjE3NjA2MTcwOTcsImVtYWlsIjoiZGFyc2hhbmEyMDIxc3VqYW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGFyc2hhbmEyMDIxc3VqYW5AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.lq5yRsDQCCq8dJ-cksvacQ8qPP6ZQx3yz4vvz9SyEWzZO8FDdlLqN_TrIOs8FJoDTzR1MU3zEmE5dB-Vb4Os_NUCdBiNq6NFKvDSqo5LrLvW9p7X0EZ6tO10LcUaQqRhEHwk8D9vOqJx7b2377GLY5E4W1bNKpdoaH77VDV94Qjhm5E4yHtMXovwUTMvks_7X3cq1-a4JByKa60rKt8at5T0dyILgNXZO_NyWWfabUZ4cOKaL36kOrYyw5rRtAK3eSXxZXgZx_x01rv6iZHHVq35lo3qT9_3ZD27ZFPXGTV-SVy0eCDWbssFHH8ZRcDcyovlDz1vFFztHLPBpvN-3Q
POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: {{auth_token}}

{
  "title": "idam nadu",
  "description": "loku case ekak nh",
  "assignedToUserId": "ff9f0c07-091a-40be-b80c-eed340e98ca7",
  "type": "document"
}